### PR TITLE
feat(tagsInput): add ability to disable the input

### LINKED ISSUE #102: Support for ng-disable
First of all, I really like this directive. Thanks to all contributors!

I have a tiny feature request: 
Forward the ng-disable attribute down to the input field so we can disable it.

### PR DESCRIPTION
**Pull request by dlukez**
Opted not to use "ng-disabled" because this would have side-effects on the directive element itself (adding the disabled attribute) which isn't really needed or intended. Instead, there's a new 'disable-input' property. I'm not sure if this is the best naming but I'll let others decide.

Styles have been added for both the bootstrap and non-bootstrap version to represent the disabled state and a CSS solution is used to hide the input and the remove buttons by default. The remove buttons could be re-shown and would still work - the developer would have to use something like pointer-events: none; if they wanted to show but disable the remove buttons (this is what bootstrap does).

The input is also disabled using 'ng-disabled', in case a developer wants to keep it shown again (since we can't prevent users from using it with CSS as far as I know).

UPDATE

Now uses `ng-disabled` :)

Closes #102

### CODE REVIEW

**Comment by oteichmann** [comment]
@mbenford Any updates on this pull? I think @dlukez is done with the implementation. So why not pull it?
I would  really appreciate it.

**Comment by jpodwys** [comment]
@mbenford I too would greatly appreciate this getting merged. I'm hoping to use this in something I'm writing, but without this merge I can't.

**Comment by AnimaLupi** [comment]
@mbenford Adding myself to the group of people waiting for the "disabled" support to be merged. Thank you for your work btw!

**Comment by mbenford** [comment]
@dlukez Could you rebase this PR on top of the master branch?

**Comment by mbenford** [comment]
I'm closing this PR since #349 will add this feature.

**Pull request closed without merging**
