### PR TITLE
feat(tagsinput): add addOnSemicolon option

### PR DESCRIPTION
**Pull request by alexanderjeurissen**
Add an option for the user to set if a new tag should be created when
the semicolon key is pressed. This is important because in larger
applications people often copy emails or data from an CSV file.

### CODE REVIEW

**Comment by gsurrel-orange** [comment]
Hi,
I don't understand why this PR is redundant with PR #179, which is only about pasting, whereas this one works while typing. Did I miss something ?

**Comment by lsojian** [comment]
Are there plans to include this PR in a release version?  As mentioned by @gsurrel-orange, PR #179 supports pasting, whereas this PR refers to typing the semicolon.  Would be very nice to have addOnSemicolon option in the final release.

**Comment by santimacia** [comment]
Please include a way to specify which chars to use, or at least accept semicolons.

**Comment by alexanderjeurissen** [comment]
I haven't been an active contributor to this project but recently saw some activity on my PR's. I'll try to elaborate on some questions and decisions on my end.

@gsurrel-orange The reason I thought of this PR to be redundant, is because in my opinion the most common usecase for tag inputs is to use a comma as separator (whilst typing) and to allow people to paste a semicolon separated list if needed.

@lsojian Another reason that I didn't move forward with this PR is that @mbenford mentioned to me that he wanted to completely refactor the `add-on-x` functionality in the future and seeing that I didn't need the `add-on-semicolon`  nor did any other contributor at that moment, made me decide to close the PR.

**Pull request closed without merging**
