### PR TITLE
fix(tagsInput): Only updating model through ng-model

### LINKED ISSUE #320: updating parent model when no value is bad
We shouldn't be setting ```scope.tags``` explicitly as that circumvents ng-model and can create invalid models on parent, especially when model hasn't been loaded yet (tags === undefined)

Consider the following scenario
```html
<tags-input ng-model="someObject.metadata.tags"></tags-input>
```

With the current code, if ```someObj``` is undefined/null, tagsInput would create the whole ```someObj.metadata``` objects as empty objects with one property ```tags``` that would be an empty array. With the only seeming reason being that you can count on running ```scope.tags.length```.  This could make the parent model invalid and cause weird side effects. Allowing for ```scope.tags``` to be undefined/null should be up to the consumer, and the value shold only be set through ```$ngModelCtrl.setViewModel()``` when the value actually changes, not through some automatic initialization. 

If you agree, I can make a PR

### PR DESCRIPTION
**Pull request by se7**
Not setting tags explicitly as that circumvents ng-model and can create invalid models on parent, especially when model hasn't been loaded yet (```scope.tags === undefined```). Removed test for testing just that and defaulted .tags to be ```[]``` in tests for them to work the way they were written. Also defaulted to updating BOTH through ```ngModel``` and direct 2-way angular binding on tags, since otherwise a lot of tests would have broken.

Can break code that relies on their model being initialized indirectly by tagsInput. Closes #320

### CODE REVIEW

**Comment by mbenford** [comment]
Could you rebase your PR on top of the master branch?

**Comment by mbenford** [comment]
Any update on this?

**Comment by se7** [comment]
done

**Comment by mbenford** [comment]
I see that you have merged the master branch into your own. Could you undo that and **rebase** your branch on top of the master branch? Let me know if you need assistance doing that.

**Comment by se7** [comment]
sorry...created this one instead https://github.com/mbenford/ngTagsInput/pull/394

**Pull request closed without merging**
