### PR TITLE
Fixed - Cannot read property 'data' of undefined

### PR DESCRIPTION
**Pull request by shlomisas**
When user unput is iess than minLength i'm getting `Cannot read property 'data' of undefined`

Source bug: https://github.com/mbenford/ngTagsInput/issues/827

### CODE REVIEW

**Comment by ewolfe** [comment]
@shlomisas any reason you closed this instead of getting it merged in? I'm experiencing the same issue.

**Comment by shlomisas** [comment]
> @shlomisas any reason you closed this instead of getting it merged in? I'm experiencing the same issue.

Yeh, bcs @mbenford doesn't merged it for a while and uts stuck on my open PR's :)

**Comment by shlomisas** [comment]
@mbenford , tests fixed - please merge when you can, others need it as well.

cc: @ewolfe

**Comment by ewolfe** [comment]
I self published this in the mean time https://github.com/ewolfe/ngTagsInput/packages/772795

**Comment by mbenford** [comment]
Hey guys. Sorry for not replying sooner.

This project is no longer maintained, and I'm to blame for not making that clear. I strongly suggest that you guys either fork it or seek out another alternative. I'm sure there are amazing libraries out there.

**Pull request closed without merging**
